export const countries = [
    {
        states: [
            {
                name: "Andaman and Nicobar",
                cities: ["Port Blair"],
            },
            {
                name: "Andhra Pradesh",
                cities: [
                    "Adoni",
                    "Amaravati",
                    "Anantpur",
                    "Chandragiri",
                    "Chittoor",
                    "Dowlaiswaram",
                    "Eluru",
                    "Guntur",
                    "Kadapa",
                    "Kakinada",
                    "Kurnool",
                    "Machilipatnam",
                    "Nagarjunakonda",
                    "Rajahmundry",
                    "Srikakulam",
                    "Tirupati",
                    "Vijayawada",
                    "Visakhapatnam",
                    "Vizianagaram",
                    "Yemmiganur",
                ],
            },
            {
                name: "Arunachal Pradesh",
                cities: ["Itanagar"],
            },
            {
                name: "Assam",
                cities: [
                    "Dhuburi",
                    "Dibrugarh",
                    "Dispur",
                    "Guwahati",
                    "Jorhat",
                    "Nagaon",
                    "Sivasagar",
                    "Silchar",
                    "Tezpur",
                    "Tinsukia",
                ],
            },
            {
                name: "Bihar",
                cities: [
                    "Ara",
                    "Barauni",
                    "Begusarai",
                    "Bettiah",
                    "Bhagalpur",
                    "Bihar Sharif",
                    "Bodh Gaya",
                    "Buxar",
                    "Chapra",
                    "Darbhanga",
                    "Dehri",
                    "Dinapur Nizamat",
                    "Gaya",
                    "Hajipur",
                    "Jamalpur",
                    "Katihar",
                    "Madhubani",
                    "Motihari",
                    "Munger",
                    "Muzaffarpur",
                    "Patna",
                    "Purnia",
                    "Pusa",
                    "Saharsa",
                    "Samastipur",
                    "Sasaram",
                    "Sitamarhi",
                    "Siwan",
                ],
            },
            {
                name: "Chhattisgarh",
                cities: [
                    "Ambikapur",
                    "Bhilai",
                    "Bilaspur",
                    "Dhamtari",
                    "Durg",
                    "Jagdalpur",
                    "Raipur",
                    "Rajnandgaon",
                ],
            },
            {
                name: "Dadra and Nagar Haveli",
                cities: ["Daman", "Diu", "Silvassa"],
            },
            {
                name: "New Delhi",
                cities: ["Delhi", "New Delhi"],
            },
            {
                name: "Goa",
                cities: ["Madgaon", "Panaji"],
            },
            {
                name: "Gujarat",
                cities: [
                    "Ahmedabad",
                    "Amreli",
                    "Bharuch",
                    "Bhavnagar",
                    "Bhuj",
                    "Dwarka",
                    "Gandhinagar",
                    "Godhra",
                    "Jamnagar",
                    "Junagadh",
                    "Kandla",
                    "Khambhat",
                    "Kheda",
                    "Mahesana",
                    "Morbi",
                    "Nadiad",
                    "Navsari",
                    "Okha",
                    "Palanpur",
                    "Patan",
                    "Porbandar",
                    "Rajkot",
                    "Surat",
                    "Surendranagar",
                    "Valsad",
                    "Veraval",
                ],
            },
            {
                name: "Haryana",
                cities: [
                    "Ambala",
                    "Bhiwani",
                    "Chandigarh",
                    "Faridabad",
                    "Firozpur Jhirka",
                    "Gurugram",
                    "Hansi",
                    "Hisaar",
                    "Jind",
                    "Kaithal",
                    "Karnal",
                    "Kurukshetra",
                    "Panipat",
                    "Pehowa",
                    "Rewari",
                    "Rohtak",
                    "Sirsa",
                    "Sonipat",
                ],
            },
            {
                name: "Himachal Pradesh",
                cities: [
                    "Bilaspur",
                    "Chamba",
                    "Dalhousie",
                    "Dharmshala",
                    "Hamirpur",
                    "Kangra",
                    "Kullu",
                    "Mandi",
                    "Nahan",
                    "Shimla",
                    "Una",
                ],
            },
            {
                name: "Jammu and Kashmir",
                cities: [
                    "Anantnag",
                    "Baramula",
                    "Doda",
                    "Gulmarg",
                    "Jammu",
                    "Kathua",
                    "Punch",
                    "Rajouri",
                    "Srinagar",
                    "Udhampur",
                ],
            },
            {
                name: "Jharkhand",
                cities: [
                    "Bokaro",
                    "Chaibasa",
                    "Deoghar",
                    "Dhanbad",
                    "Dumka",
                    "Giridih",
                    "Hazaribagh",
                    "Jamshedpur",
                    "Jhaeia",
                    "Rajmahal",
                    "Ranchi",
                    "Saraikela",
                ],
            },
            {
                name: "Karnataka",
                cities: [
                    "Badami",
                    "Ballari",
                    "Bengaluru",
                    "Belagavi",
                    "Bhadravati",
                    "Bidar",
                    "Chikamagaluru",
                    "Chitradurga",
                    "Devangere",
                    "Halebid",
                    "Hassan",
                    "Hubbali-Dharwad",
                    "Kalaburagi",
                    "Kolar",
                    "Madikeri",
                    "Mandya",
                    "Mangaluru",
                    "Mysuru",
                    "Raichur",
                    "Shiamogga",
                    "Shravanabelagola",
                    "Shrirangapattana",
                    "Tumakuru",
                    "Vijayapura",
                ],
            },
            {
                name: "Kerala",
                cities: [
                    "Alappuzha",
                    "Vatakara",
                    "Idukki",
                    "Kannur",
                    "Kochi",
                    "Kollam",
                    "Kottayam",
                    "Kozhikode",
                    "Mattancheri",
                    "Palakkad",
                    "Thalassery",
                    "Thiruvananthapuram",
                    "Thrissur",
                ],
            },
            {
                name: "Ladakh",
                cities: ["Kargil", "Leh"],
            },
            {
                name: "Madhya Pradesh",
                cities: [
                    "Balaghat",
                    "Barwani",
                    "Betul",
                    "Bharhut",
                    "Bhind",
                    "Bhojpur",
                    "Bhopal",
                    "Burhanpur",
                    "Chhatarpur",
                    "Chhindwara",
                    "Damoh",
                    "Datia",
                    "Dewas",
                    "Dhar",
                    "Dr. Ambedkar Nagar (Mhow)",
                    "Guna",
                    "Gwalior",
                    "Hoshangabad",
                    "Indore",
                    "Itarsi",
                    "Jabalpur",
                    "Jhabua",
                    "Khajuraho",
                    "Khandwa",
                    "Khargone",
                    "Maheshwar",
                    "Mandla",
                    "Mandsaur",
                    "Morena",
                    "Murwara",
                    "Narsimhapur",
                    "Narsinghgarh",
                    "Narwar",
                    "Neemuch",
                    "Nowgong",
                    "Orchha",
                    "Panna",
                    "Raisen",
                    "Rajgarh",
                    "Ratlam",
                    "Rewa",
                    "Sagar",
                    "Sarangpur",
                    "Satna",
                    "Sehore",
                    "Seoni",
                    "Shahdol",
                    "Shajapur",
                    "Sheopur",
                    "Shivpuri",
                    "Ujjain",
                    "Vidisha",
                ],
            },
            {
                name: "Maharashtra",
                cities: [
                    "Ahmadnagar",
                    "Akola",
                    "Amravati",
                    "Aurangabad",
                    "Bhandara",
                    "Bhusawal",
                    "Bid",
                    "Buldhana",
                    "Chandrapur",
                    "Daulatabad",
                    "Dhule",
                    "Jalgaon",
                    "Kalyan",
                    "Karli",
                    "Kolhapur",
                    "Mahabaleshwar",
                    "Malegaon",
                    "Matheran",
                    "Mumbai",
                    "Nagpur",
                    "Nanded",
                    "Nashik",
                    "Osmanabad",
                    "Pandharpur",
                    "Parbhani",
                    "Pune",
                    "Ratnagiri",
                    "Sangli",
                    "Satara",
                    "Sevagram",
                    "Solapur",
                    "Thane",
                    "Ulhasnagar",
                    "Vasai-Virar",
                    "Wardha",
                    "Yavatmal",
                ],
            },
            {
                name: "Manipur",
                cities: ["Imphal"],
            },
            {
                name: "Meghalaya",
                cities: ["Cherapunji", "Shillong"],
            },
            {
                name: "Mizoram",
                cities: ["Aizwal", "Lunglei"],
            },
            {
                name: "Nagaland",
                cities: ["Kohima", "Mon", "Phek", "Wokha", "Zunheboto"],
            },
            {
                name: "Odisha",
                cities: [
                    "Balangir",
                    "Baleshwar",
                    "Baripada",
                    "Bhubaneshwar",
                    "Brahmapur",
                    "Cuttack",
                    "Dhenkanal",
                    "Kendujhar",
                    "Konark",
                    "Koraput",
                    "Paradip",
                    "Phulabani",
                    "Puri",
                    "Sambalpur",
                    "Udayagiri",
                ],
            },
            {
                name: "Puducherry",
                cities: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
            },
            {
                name: "Punjab",
                cities: [
                    "Amritsar",
                    "Batala",
                    "Chandigarh",
                    "Faridkot",
                    "Firozpur",
                    "Gurdaspur",
                    "Hoshiarpur",
                    "Jalandhar",
                    "Kapurthala",
                    "Ludhiana",
                    "Nabha",
                    "Patiala",
                    "Rupnagar",
                    "Sangrur",
                ],
            },
            {
                name: "Rajasthan",
                cities: [
                    "Abu",
                    "Ajmer",
                    "Alwar",
                    "Amer",
                    "Barmer",
                    "Beawar",
                    "Bharatpur",
                    "Bhilwara",
                    "Bikaner",
                    "Bundi",
                    "Chittaurgarh",
                    "Churu",
                    "Dhaulpur",
                    "Dungarpur",
                    "Ganganagar",
                    "Hanumangarh",
                    "Jaipur",
                    "Jaisalmer",
                    "Jalor",
                    "Jhalawar",
                    "Jhunjhunu",
                    "Jodhpur",
                    "Kishangarh",
                    "Kota",
                    "Merta",
                    "Nagaur",
                    "Nathdwara",
                    "Pali",
                    "Phalodi",
                    "Pushkar",
                    "Sawai Madhopur",
                    "Shahpura",
                    "Sikar",
                    "Sirohi",
                    "Tonk",
                    "Udaipur",
                ],
            },
            {
                name: "Sikkim",
                cities: ["Gangatok", "Gyalshing", "Lachung", "Mangan"],
            },
            {
                name: "Tamil Nadu",
                cities: [
                    "Arcot",
                    "Chengalpattu",
                    "Chennai",
                    "Chidambaram",
                    "Coimbatore",
                    "Cuddalore",
                    "Dharmapuri",
                    "Dindigul",
                    "Erode",
                    "Kanchipuram",
                    "Kanniyakumari",
                    "Kodaikanal",
                    "Kumbakonam",
                    "Madurai",
                    "Mamallapuram",
                    "Nagappattinam",
                    "Nagercoil",
                    "Palayamkottai",
                    "Pudukkottai",
                    "Rajapalayam",
                    "Ramanathapuram",
                    "Salem",
                    "Thanjavur",
                    "Tiruchchirappalli",
                    "Tirunelveli",
                    "Tiruppur",
                    "Thoothukudi",
                    "Udhagamandalam",
                    "Vellore",
                ],
            },
            {
                name: "Telangana",
                cities: [
                    "Hyderabad",
                    "Karimnagar",
                    "Khammam",
                    "Mahbubnagar",
                    "Nizamabad",
                    "Sangareddi",
                    "Warangal",
                ],
            },
            {
                name: "Tripura",
                cities: ["Agartala"],
            },
            {
                name: "Uttar Pradesh",
                cities: [
                    "Agra",
                    "Aligarh",
                    "Amroha",
                    "Ayodhya",
                    "Azamgarh",
                    "Bahraich",
                    "Ballia",
                    "Banda",
                    "Bara Banki",
                    "Bareilly",
                    "Basti",
                    "Bijnor",
                    "Bithur",
                    "Budaun",
                    "Bulandshahr",
                    "Deoria",
                    "Etah",
                    "Etawah",
                    "Faizabad",
                    "Farrukhabad-cum-Fatehgarh",
                    "Fatehpur",
                    "Fatehpur Sikri",
                    "Ghaziabad",
                    "Ghazipur",
                    "Gonda",
                    "Gorakhpur",
                    "Hamirpur",
                    "Hardoi",
                    "Hathras",
                    "Jalaun",
                    "Jaunpur",
                    "Jhansi",
                    "Kannauj",
                    "Kanpur",
                    "Lakhimpur",
                    "Lalitpur",
                    "Lucknow",
                    "Mainpuri",
                    "Mathura",
                    "Meerut",
                    "Mirzapur-Vindhyachal",
                    "Moradabad",
                    "Muzaffarnagar",
                    "Partapgarh",
                    "Pilibhit",
                    "Prayagraj",
                    "Rae Bareli",
                    "Rampur",
                    "Saharanpur",
                    "Sambhal",
                    "Shahjahanpur",
                    "Sitapur",
                    "Sultanpur",
                    "Tehri",
                    "Varanasi",
                ],
            },
            {
                name: "Uttarakhand",
                cities: [
                    "Almora",
                    "Dehra Dun",
                    "Haridwar",
                    "Mussoorie",
                    "Nainital",
                    "Pithoragarh",
                ],
            },
            {
                name: "West Bengal",
                cities: [
                    "Alipore",
                    "Alipur Duar",
                    "Asansol",
                    "Baharampur",
                    "Bally",
                    "Balurghat",
                    "Bankura",
                    "Baranagar",
                    "Barasat",
                    "Barrackpore",
                    "Basirhat",
                    "Bhatpara",
                    "Bishnupur",
                    "Budge Budge",
                    "Burdwan",
                    "Chandernagore",
                    "Darjeeling",
                    "Diamond Harbour",
                    "Dum Dum",
                    "Durgapur",
                    "Halisahar",
                    "Haora",
                    "Hugli",
                    "Ingraj Bazar",
                    "Jalpaiguri",
                    "Kalimpong",
                    "Kamarhati",
                    "Kanchrapara",
                    "Kharagpur",
                    "Cooch Behar",
                    "Kolkata",
                    "Krishnanagar",
                    "Malda",
                    "Midnapore",
                    "Murshidabad",
                    "Nabadwip",
                    "Palashi",
                    "Panihati",
                    "Purulia",
                    "Raiganj",
                    "Santipur",
                    "Shantiniketan",
                    "Shrirampur",
                    "Siliguri",
                    "Siuri",
                    "Tamluk",
                    "Titagarh",
                ],
            },
        ],
    },
];